# Generated by Django 5.2.1 on 2025-05-22 19:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du tournoi')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('lieu', models.CharField(blank=True, max_length=100, verbose_name='Lieu')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournois_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tournoi',
                'verbose_name_plural': 'Tournois',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='MatchTournoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_match', models.DateTimeField(verbose_name='Date et heure du match')),
                ('lieu_match', models.CharField(blank=True, max_length=100, verbose_name='Lieu du match')),
                ('arbitre', models.CharField(blank=True, max_length=100, verbose_name='Arbitre')),
                ('remarques', models.TextField(blank=True, verbose_name='Remarques')),
                ('score_domicile', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Score équipe domicile')),
                ('score_exterieur', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Score équipe extérieure')),
                ('termine', models.BooleanField(default=False, verbose_name='Match terminé')),
                ('equipe_domicile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchs_domicile', to='equipes.equipe')),
                ('equipe_exterieur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchs_exterieur', to='equipes.equipe')),
                ('tournoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchs_tournoi', to='tournois.tournoi')),
            ],
            options={
                'verbose_name': 'Match de tournoi',
                'verbose_name_plural': 'Matchs de tournoi',
                'ordering': ['date_match'],
            },
        ),
        migrations.CreateModel(
            name='InscriptionTournoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions_tournois', to='equipes.equipe')),
                ('tournoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='tournois.tournoi')),
            ],
            options={
                'verbose_name': 'Inscription à un tournoi',
                'verbose_name_plural': 'Inscriptions aux tournois',
                'unique_together': {('equipe', 'tournoi')},
            },
        ),
    ]
