# Generated by Django 5.2 on 2025-05-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournois', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournoi',
            name='nombre_equipes_max',
            field=models.PositiveIntegerField(default=16, verbose_name="Nombre maximum d'équipes"),
        ),
    ]
