# Generated by Django 5.2.1 on 2025-05-28 08:45

import tournois.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournois', '0002_tournoi_nombre_equipes_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournoi',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=tournois.models.tournament_logo_path, verbose_name='Logo du tournoi'),
        ),
    ]
