# Generated by Django 5.2 on 2025-05-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('responsable', "Responsable d'équipe")], default='responsable', max_length=20),
        ),
    ]
