# Generated by Django 5.2.1 on 2025-05-17 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_type'),
    ]

    operations = [
    ]
