# Generated by Django 5.2.1 on 2025-05-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_options_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('participant', 'Participant'), ('responsable', "Responsable d'équipe"), ('organisateur', 'Organisateur')], default='invite', max_length=20, verbose_name='Type de compte'),
        ),
    ]
