# Generated by Django 5.2.1 on 2025-05-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_update_user_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('participant', 'Participant'), ('responsable', "Responsable d'équipe"), ('organisateur', 'Organisateur')], default='participant', max_length=20, verbose_name='Type de compte'),
        ),
    ]
