# Generated by Django 5.2.1 on 2025-05-28 09:07

import accounts.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customuser_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='date_updated',
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_derniere_connexion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='code_postal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='pays',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='preference_langue',
            field=models.CharField(default='fr', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='profile',
            name='telephone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='ville',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('participant', 'Participant'), ('responsable', 'Responsable'), ('organisateur', 'Organisateur'), ('admin', 'Administrateur')], default='participant', max_length=20, verbose_name="Type d'utilisateur"),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_all', models.BooleanField(default=True, verbose_name='Activer toutes les notifications')),
                ('sound_enabled', models.BooleanField(default=True, verbose_name='Activer les sons de notification')),
                ('match_notifications', models.BooleanField(default=True, verbose_name='Notifications de matchs')),
                ('tournament_notifications', models.BooleanField(default=True, verbose_name='Notifications de tournois')),
                ('team_notifications', models.BooleanField(default=True, verbose_name="Notifications d'équipe")),
                ('result_notifications', models.BooleanField(default=True, verbose_name='Notifications de résultats')),
                ('email_delivery', models.BooleanField(default=True, verbose_name='Recevoir par email')),
                ('push_delivery', models.BooleanField(default=False, verbose_name='Notifications push')),
                ('digest_enabled', models.BooleanField(default=False, verbose_name='Activer le résumé des notifications')),
                ('digest_frequency', models.CharField(choices=[('daily', 'Quotidien'), ('weekly', 'Hebdomadaire')], default='daily', max_length=10, verbose_name='Fréquence du résumé')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Préférence de notification',
                'verbose_name_plural': 'Préférences de notification',
            },
        ),
    ]
