# Generated by Django 5.2 on 2025-05-24 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipes', '0001_initial'),
        ('tournois', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('lieu', models.CharField(blank=True, max_length=100, null=True)),
                ('score_equipe_a', models.PositiveIntegerField(blank=True, null=True)),
                ('score_equipe_b', models.PositiveIntegerField(blank=True, null=True)),
                ('termine', models.BooleanField(default=False)),
                ('equipe_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchs_equipe_a', to='equipes.equipe')),
                ('equipe_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchs_equipe_b', to='equipes.equipe')),
                ('tournoi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matchs_amicaux', to='tournois.tournoi')),
            ],
        ),
    ]
