# Generated by Django 5.2.1 on 2025-05-28 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes supplémentaires'),
        ),
        migrations.AddField(
            model_name='match',
            name='type_match',
            field=models.CharField(choices=[('tournoi', 'Match de tournoi'), ('amical', 'Match amical')], default='tournoi', max_length=10),
        ),
    ]
