# Generated by Django 5.2.1 on 2025-05-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membreequipe',
            name='jersey_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numéro de maillot'),
        ),
    ]
