# Generated by Django 5.2.1 on 2025-05-24 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipes', '0002_membreequipe_jersey_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membreequipe',
            name='jersey_number',
        ),
    ]
