# Generated by Django 5.2.1 on 2025-05-28 01:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('lien', models.CharField(blank=True, max_length=255, null=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('lu', models.BooleanField(default=False)),
                ('type_notification', models.CharField(choices=[('info', 'Information'), ('match_amical', 'Match amical'), ('tournoi', 'Tournoi'), ('equipe', 'Équipe'), ('resultat', 'Résultat')], default='info', max_length=20)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
            },
        ),
    ]
